LEARNING_RATE = 1e-5
TRAIN_EPOCHS = 10000
WEIGHT_DECAY = 0.0

LOG_INTERVAL = 200
CHECKPOINT_STEPS = 25000

TRAIN_STRIDE = 1
VAL_STRIDE = 10
NUM_GUARD_FRAMES = 60
DOWNSAMPLE_FACTOR = "2-8125"

MIXED_PRECISION = False
RELOAD_MODEL = True



# calculations
import torch
if MIXED_PRECISION:
    MODEL_DTYPE = torch.float16
else:
    MODEL_DTYPE = torch.float32